### ISSUE TITLE
SVG icon looks different after being converted to woff

### ISSUE THREAD

**Issue by nickspiel** [nfroidure/gulp-iconfont#105]
When the svgs are converted to woff the line weights are changed and become wobbly. I have created this [stackoverflow question](http://stackoverflow.com/questions/34666129/svg-icon-looks-different-after-being-converted-to-woff) with a full description of the issue.

**Comment by yairEO** [comment]
why was this closed? I have the same issue. Just migrated all my project's icons from **icomoon** and they all look like sh*t inside the generated TTF :/

**Comment by nickspiel** [comment]
What size are your icons?

**Comment by TylerYang** [comment]
Actually I have the same issue last day, and just like @yairEO  said, it will be fixed by setting:

```javascript
fontHeight: 1001, //(>= 1000)
normalize: true
```
Also this have been documented in the end of the usage section of the [README]( https://github.com/nfroidure/gulp-iconfont#usage)
But I think I will be better to update the document so that the other developers won't ignored that part.

**Comment by yairEO** [comment]
@nickspiel - 16px

@TylerYang - I think the README section `500 is a minimum` should be in bold :) easily missed
