### ISSUE TITLE
font is vertical error like this.

### ISSUE THREAD

**Issue by hkongm** [nfroidure/gulp-iconfont#42]
to see the `www/iconfont.html` in [repo](https://github.com/hkongm/iconfontcssdemo)

I tried fontHeight/normalize/descent, these not work at all.

Please help me.

**Comment by nfroidure** [comment]
Won't without a better explanation of your problem. https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

**Comment by hkongm** [comment]
update the screenshot.
![pic](http://caichao.me/temp/iconfonterror.png)

**Comment by hkongm** [comment]
please watch the screenshot.

**Comment by nfroidure** [comment]
i'll try to have a deeper look to this in about a week or 2. in the meanwhile, i think you should remove the transformations from your SVG icons since the problem probably comes from a bad transformation handling by svgicons2svgfont.

If confirmed, please add an issue to the mentioned above project and i'll look at this transformation bug specifically.

**Comment by hkongm** [comment]
thanks the tip.
i tried to delete the transform, the icon will move down for some pixels, but still not correct.

**Comment by nfroidure** [comment]
Note that you cannot just remove this attribute but you also have to translate the shapes contained in your glyph (using a SVG editor while being careful it doesn't add transforms or a JS lib, say https://github.com/nfroidure/SVGPathData ;) )
