### ISSUE TITLE
basline vs- glyph-size issue

### ISSUE THREAD

**Issue by bm2u** [nfroidure/gulp-iconfont#52]
Unfortunately I've got an issue concerning the line-height/baseline of my generated font. There is a lot of space beneath the glyphs. So ist does not fit in it's html-parent element. I hope the image can give a flavor of what I am talking about. On the left hand is a glyph of my font. On the opposite side you see a glyph of font-awesome (as an working example). Line 2 -> my font selected | Line 3 -> font awesome glyph selected. Any ideas?
![font_size_bm2u](https://cloud.githubusercontent.com/assets/11159476/8159502/9791da54-1367-11e5-9e04-bed71bf1fe40.jpg)

**Comment by nfroidure** [comment]
Hard to help without a full working project reproducing the issue. Seems you are missing the descent option though. Try to play with the various options of the frontend generator http://nfroidure.github.io/svgiconfont/

**Comment by bm2u** [comment]
The options are as follows.
fontName: 'myFont',
appendUnicode: true,
normalize: true,
fontHeight: 512,
descent: 70
By the way: same behavior with your twitter.svg for testing purposes.

**Comment by nfroidure** [comment]
Try to update to gulp-iconfont 2.0.2, i assume you use an older version since appendCodepoint doesn't exists anymore.

Then, check the vertical alignment of all your icons. In fact, gulp-iconfont won't center them vertically for you. I see you use the normalize option, it does'nt magically fix the baseline of the icons. In fact, the normalize option should only be used with icons without extra space under them.

If after all that checks the problem still persists, you'll have to provide a gist/github project reproducing the issue to get further help. Here is an example of relevant issue https://github.com/nfroidure/gulp-iconfont/issues/9 .

**Comment by bm2u** [comment]
gulp-iconfont 2.0.2 ist not available. I am using the latest version 2.0.0 and use appendUnicode instead of appendCodepoint. I'm gonna check my environment and drop you comment, if the problem remains

**Comment by bm2u** [comment]
Got the solution: one of my svg files were corrupted, but determined the max-icon-height. After fixing the source file, everything went excellent.
