### ISSUE TITLE
svg2ttf timestamp option

### ISSUE THREAD

**Issue by suisho** [nfroidure/gulp-iconfont#56]
Thank you for append [timestamp option to gulp-svg2ttf](https://github.com/nfroidure/gulp-svg2ttf/commit/365080d98cd39c3fabbd6ddad0f478e330b9d6bf). :smiley: 

And I want this option to gulp-iconfont too.
(I tried to make pull request, but couldn't solve some tests...)

**Comment by nfroidure** [comment]
I planned to but completely forgotten. Thank for the reminder ;). My global.Date monkey patch https://github.com/nfroidure/gulp-iconfont/blob/master/tests/tests.mocha.js#L11 override the timestamp to 3600 so a option.timestampt to 3 in tests should work (since svg2ttf rounds it to seconds instead of ms).

You PR would of course be accepted, otherwise, i'll try to do it next week.

**Comment by nfroidure** [comment]
Also there is things to compile, the woff2_compress binary to set in the env PATH... https://github.com/nfroidure/gulp-iconfont/blob/master/.travis.yml

But Your PR will be ran by Travis and you'll see if it works. In any case, this will help me ;).

**Comment by suisho** [comment]
Thank you for advice! 
I send #58

**Comment by nfroidure** [comment]
Nice work :).
