### ISSUE TITLE
gulp-ttf2woff2: ttf2woff2@1.1.0 Installation fails (build error)

### ISSUE THREAD

**Issue by bm2u** [nfroidure/gulp-iconfont#60]
When I update from version 2.0.0 to 3.0.2 the installation of ttf2woff2 failes with the following log:
```
(node-gyp rebuild > builderror.log) || (exit 0)
child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\projects\myproject\node_modules\gulp-iconfont\node_modules\gulp-ttf2woff2\node_modules\ttf2woff2
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

__system config:__
+ Windows 8.1 64-bit
+ MS Visual Studio 2013 Express
+ node v0.12.0
+ npm 2.5.1
+ node-gyp@1.0.2

I tried to install the latest version with `npm install gulp-iconfont --msvs_version=2013` without success. 
Paradoxically, the woff2-file has been created.

Suggestion:
*It seems to me MS Visual Studio is a requirement to use gulp-iconfont 3.0.2. If so, it should be mentioned in the README.md*

**Comment by nfroidure** [comment]
https://github.com/nfroidure/gulp-iconfont/issues/61

**Comment by nfroidure** [comment]
Hi! Can you answer to the questions in this issue? https://github.com/nfroidure/gulp-iconfont/issues/61#issuecomment-114888446

Thanks in advance.

**Comment by bm2u** [comment]
@nfroidure: sure - 
`npm i` -> *no results*
*node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2* __does exist__
__console log:__
```
gulp-svgicons2svgfont: Font created
Warning: Enlarging memory arrays, this is not fast! 16777216,33554432
enlarged memory arrays from 16777216 to 33554432, took 9 ms (has ArrayBuffer.transfer? false)
Warning: Enlarging memory arrays, this is not fast! 33554432,134217728
enlarged memory arrays from 33554432 to 134217728, took 32 ms (has ArrayBuffer.transfer? false)
Warning: Enlarging memory arrays, this is not fast! 134217728,268435456
enlarged memory arrays from 134217728 to 268435456, took 133 ms (has ArrayBuffer.transfer? false)
```
woff2-font has been created, __unless__ I set the option `spawnWoff2: true`
__console log:__
```
[16:45:31] gulp-svgicons2svgfont: Font created
d:\projects\myproject\node_modules\gulp-iconfont\node_modules\gulp-ttf2woff2\node_modules\ttf2woff2\jssrc\ttf2woff2.js:90
      throw ex;
throw ex;
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at Socket._writeGeneric (net.js:681:26)
    at Socket._write (net.js:700:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:625:40)
    at PassThrough.stream._transform (d:\projects\myproject\node_modules\gulp-iconfont\node_modules\gulp-spawn\index.js:84:18)
    at PassThrough.Transform._read (_stream_transform.js:179:10)
    at PassThrough.Transform._write (_stream_transform.js:167:12)

Process finished with exit code 7
```

**Comment by nfroidure** [comment]
Ok, so it is just the normal behavior since you're running Windows and you don't have anything installed to build native NodeJS add-on.

It fallbacks to the JS version that is slower but works. The spawnWoff2 option exists to use the woff2_compress binary if you built and installed it on your system which is actually not the case according to your pastes.

**Comment by Vlasterx** [comment]
Same happens to me. WOFF2 file is not made.

**Comment by nfroidure** [comment]
@Vlasterx are you aware that woff2 is an option that defaults to false? https://github.com/nfroidure/gulp-iconfont#iconfontoptions

**Comment by Vlasterx** [comment]
I am aware, I have read about it after this comment. It seems that it is a problem only on windows? I was hoping that it can be fixed.

**Comment by nfroidure** [comment]
Everything can be fixed with any informations and feedback on the actual error. You should find some other issues here about windows troubles.

On the other hand, you'll have to wait for a nice person working on Windows and willing help you to fix it since i actually do no want to support windows by myself and prefer relying on the windows community to fix those problems.

May take a while though.

**Comment by Vlasterx** [comment]
That's ok. I understand that this is hard work and that we can only rely on your good will to support your work. Thank you for your willingness to create this in the first place since it has helped me a lot in my design and in some design related research.

All best and I really hope that you won't flush down the drain all Windows users. Don't let this fall apart, you have done a great job so far!

All best.

**Comment by lreece** [comment]
Same issue on Windows. Just keeping an eye on this.
